FROM openjdk:11
COPY ./build/libs/sampleserviceone-0.0.1-SNAPSHOT.jar /usr/app/somepleserviceone.jar
CMD echo 'starting application' & java -jar /usr/app/somepleserviceone.jar --secrets.secret1='Captain America' --secrets.secret2='Hulk'